/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BerfChat } from "./BerfChat";

export { BerfChat__factory } from "./factories/BerfChat__factory";
