/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BerfChatStorage } from "./BerfChatStorage";

export { BerfChatStorage__factory } from "./factories/BerfChatStorage__factory";
